### ISSUE TITLE
Get National Reproduction Number of 2020

### ISSUE THREAD

**Issue by Itaymanes** [epiforecasts/covid-rt-estimates#198] opened 2021-05-10 07:08 UTC
Hello,

Thank you for the great and very useful datasets. I am looking into estimates of the National Reproduction Number R (based on reported\death cases), but I can't find these estimations before December 2020.

for example [here](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/TTLQRN), the 'growth_rate.tab' file it's exactly what I am looking for, but 2020 is completely absent 

Is there a way to download the R estimation for the full period, i.e. 2020-2021?

Thanks in advance!

**Comment by joeHickson** [comment] 2021-05-10 07:36
Hi Itay,

Currently production runs on a 16 week window of data. We are almost there with full timeseries though! #197 #15 
It should be available to run yourself now (caveat emporum - bleeding edge and not been thoroughly tested yet) and we will be looking to get our infrastructure processing it in the coming weeks. @zmaalick can hopefully update this ticket when we have results. Is there a particular dataset you are looking for? Given the anticipated compute involved we intend to space out running the various datasets over a month.

Thanks

Joe

**Comment by Itaymanes** [comment] 2021-05-10 10:47
Thank you.

Our wish is to have a .csv file with the Reproduction Number estimates, from January 2020 till May 2021. Similar to what you have [here](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/RBZVJE) in 'rt' file (country-level estimates for each day), but with more dates (including 2020).

We need it for research purposes, as a reliable data source for R values. This will make it significantly easier for us to just download the full data as a csv file, instead of generating the R values from scratch.

**Comment by jojo453** [comment] 2021-05-19 16:18
Hi, I too would be interested in the Rt calculations for deaths and cases for each country and subnational unit for 2020,
Thanks
Joe

**Comment by sbfnk** [comment] 2021-11-26 17:09
Closing as duplicate of https://github.com/epiforecasts/covid-rt-estimates/issues/15

**Closed by sbfnk** 2021-11-26 17:09 UTC
Labels: duplicate
