### ISSUE TITLE
Update/upgrade documentation

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-rt-estimates#91] opened 2020-10-16 10:19 UTC
Current documentation in the README is very targeted at those wishing to reproduce results. In reality, this will be a very small subset of the user base with most people interested in where to find the estimates, how to interact with them, the update schedule, and potentially links out to downstream uses of them.

Opened this issue to start a discussion on what an improved structure could be.

**Comment by joeHickson** [comment] 2020-10-21 11:03
duplicate of #107 - I think the discussion is on there now

**Closed by joeHickson** 2020-10-21 11:03 UTC
Labels: documentation, question
